# Generated by Django 5.0.3 on 2024-03-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='color',
            new_name='colour',
        ),
    ]
